// Code generated by goctl. DO NOT EDIT!
// Source: calculation.proto

package server

import (
	"context"

	"gosummary/gozero/trafficcalculation/cmd/rpc/internal/logic"
	"gosummary/gozero/trafficcalculation/cmd/rpc/internal/svc"
	"gosummary/gozero/trafficcalculation/cmd/rpc/pb"
)

type TrafficCalculationServer struct {
	svcCtx *svc.ServiceContext
	pb.UnimplementedTrafficCalculationServer
}

func NewTrafficCalculationServer(svcCtx *svc.ServiceContext) *TrafficCalculationServer {
	return &TrafficCalculationServer{
		svcCtx: svcCtx,
	}
}

//  查询拥堵状态
func (s *TrafficCalculationServer) QueryCurrentTraffic(ctx context.Context, in *pb.QueryReq) (*pb.TrafficStatusResp, error) {
	l := logic.NewQueryCurrentTrafficLogic(ctx, s.svcCtx)
	return l.QueryCurrentTraffic(in)
}
