// Code generated by goctl. DO NOT EDIT.
package types

type Box struct {
	LatMax float64 `json:"lat_max"`
	LatMin float64 `json:"lat_min"`
	LngMax float64 `json:"lng_max"`
	LngMin float64 `json:"lng_min"`
}

type TrafficStatusReq struct {
	LaneId int64 `json:"laneId"` // 道路ID
}

type LaneLevel struct {
	LaneId int64 `json:"lane_id"`
	Level  int64 `json:"level"`
}

type TrafficStatusResp struct {
	Code int       `json:"code"`
	Msg  string    `json:"msg"`
	Data LaneLevel `json:"data"`
}
