// Code generated by goctl. DO NOT EDIT.
package types

type SendArgs struct {
}

type SendReply struct {
	Code int64  `json:"code"`
	Msg  string `json:"msg"`
}

type FindArgs struct {
	Id int64 `json:"id"`
}

type FindReply struct {
	ToMail string `json:"toMail"`
	Code   int64  `json:"code"`
	Msg    string `json:"msg"`
}
